version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    expose:
      - 2379/tcp
    volumes:
      - etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    expose:
      - 9001/tcp
      - 9000/tcp
    volumes:
      - minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    image: milvusdb/milvus:v2.3.10
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    expose:
      - 19530/tcp
      - 9091/tcp
    depends_on:
      - etcd
      - minio

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: 

  ollama:
    image: ollama/ollama
    expose:
     - 11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    environment:
      - OLLAMA_DEBUG=1
    command: serve
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]

  backend:
    build:
      context: .
      dockerfile: ./dockerfile.backend
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - milvus
      - ollama
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_ENDPOINT=/api/embeddings

volumes:
  etcd:
  minio:
  milvus:
  ollama:

networks:
  default:
    name: milvus